server:
  port: 18080
  tomcat:
    max-threads: 200
    uri-encoding: UTF-8
spring:
  profiles:
    active:
      - mail
  mvc:
    static-path-pattern: /**
  resources:
    static-locations: classpath:/static/
  servlet:
    multipart:
      enabled: true
      maxFileSize: -1
  datasource:
    url: jdbc:mysql://localhost:3307/sawca?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8
    username: root
    password: '_Jj43^66'
  data:
    mongodb:
      uri: mongodb://localhost:27017/sawca
  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        format_sql: true
    show-sql: true
    open-in-view: on
mybatis-plus:
  mapper-locations: classpath*:/mapper/**/**Mapper.xml
