mybatis-plus:
  mapper-locations: classpath*:/mapper/**/**Mapper.xml
server:
  port: 18080
  tomcat:
    max-threads: 200
    uri-encoding: UTF-8
logging:
  file:
    max-history: 30
    path: /home/demo/log/
  level:
    root: warn
spring:
  servlet:
    multipart:
      enabled: true
      maxFileSize: -1
  mvc:
    static-path-pattern: /**
  resources:
    static-locations: classpath:/static/
  datasource:
    url: jdbc:mysql://localhost:3306/sawca?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8
    username: root
    password: 'mcxxkj2020@db04'
  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        format_sql: true
    show-sql: true
    open-in-view: false
wozhitu:
  api:
    host: http://www.tudatech.com:8086
    #    host: http://localhost:18086
    key-fast: guangzhouMrHuangGongAnProj20191126H1_simph2type2
    key-accurate: guangzhouMrHuangGongAnProj20191126H1_recog
    search-fast: /vsearchtech/api/v1.0/apisim_search
    search-accurate: /vsearchtech/api/v1.0/apipnp_search
    add-fast: /vsearchtech/api/v1.0/apisim_additem
    add-accurate: /vsearchtech/api/v1.0/apipnp_additem
    delete-fast: /vsearchtech/api/v1.0/apisim_deleteitem
    delete-accurate: /vsearchtech/api/v1.0/apipnp_deleteitem
